server.port: 9966
spring.profiles: default
comaco.security.jwt:
  tokenExpirationTime: 15 # Number of minutes
  refreshTokenExpTime: 60 # Minutes
  tokenIssuer: http://tecnopro.net
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
  
#spring.datasource:
#  url: "jdbc:h2:mem:testdb"
#  driverClassName: org.h2.Driver
#  username: sa
#  password: ""
#  data: "classpath*:data.sql"
#spring.jpa:
#  database-platform: org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled: true


spring.datasource:
  platform: postgres
  url: "jdbc:postgresql://localhost:5432/smc_base"
  username: smc_admin
  password: c0mac0ABc
  data: "classpath*:data.sql"
spring.jpa:
  database: POSTGRESQL
  show-sql: false
  generate-ddl: true
  hibernate.ddl-auto: update
  properties.hibernate.jdbc.lob.non_contextual_creation: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  hibernate.naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  properties.hibernate.enable_lazy_load_no_trans: true

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS: false
spring.h2.console.enabled: false
